from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "app.db"
DATABASE_URL = f"sqlite:///{DB_PATH.as_posix()}"

JWT_SECRET = "course-project-demo-secret"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
AUTH_CODE_EXPIRE_MINUTES = 10

SERVER_HOST = "127.0.0.1"
AUTH_SERVER_PORT = 8000
CLIENT_APP_PORT = 8001
RESOURCE_SERVER_PORT = 8002

AUTH_SERVER_BASE = f"http://{SERVER_HOST}:{AUTH_SERVER_PORT}"
CLIENT_APP_BASE = f"http://{SERVER_HOST}:{CLIENT_APP_PORT}"
RESOURCE_SERVER_BASE = f"http://{SERVER_HOST}:{RESOURCE_SERVER_PORT}"

DEFAULT_CLIENT_ID = "demo-client"
DEFAULT_CLIENT_SECRET = "course-client-secret"
DEFAULT_REDIRECT_URI = f"{CLIENT_APP_BASE}/callback"

ENABLE_PKCE = False
DEFAULT_PKCE_METHOD = "S256"
ALLOWED_PKCE_METHODS = {"plain", "S256"}
